// Code generated by protoc-gen-go.
// source: credit.proto
// DO NOT EDIT!

/*
Package cheshbown_proto is a generated protocol buffer package.

It is generated from these files:
	credit.proto

It has these top-level messages:
	Base
	Work
	Worker
*/
package cheshbown_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_WORK       MessageType = 0
	MessageType_DISCONNECT MessageType = 1
	MessageType_SHUTDOWN   MessageType = 2
	MessageType_RESULT     MessageType = 3
	MessageType_GOSSIP     MessageType = 4
)

var MessageType_name = map[int32]string{
	0: "WORK",
	1: "DISCONNECT",
	2: "SHUTDOWN",
	3: "RESULT",
	4: "GOSSIP",
}
var MessageType_value = map[string]int32{
	"WORK":       0,
	"DISCONNECT": 1,
	"SHUTDOWN":   2,
	"RESULT":     3,
	"GOSSIP":     4,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Result int32

const (
	Result_ACK  Result = 0
	Result_NACK Result = 1
)

var Result_name = map[int32]string{
	0: "ACK",
	1: "NACK",
}
var Result_value = map[string]int32{
	"ACK":  0,
	"NACK": 1,
}

func (x Result) String() string {
	return proto.EnumName(Result_name, int32(x))
}
func (Result) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type NodeType int32

const (
	NodeType_Distributor        NodeType = 0
	NodeType_LenderSupervisor   NodeType = 1
	NodeType_Lender             NodeType = 2
	NodeType_BorrowerSupervisor NodeType = 3
	NodeType_Borrower           NodeType = 4
)

var NodeType_name = map[int32]string{
	0: "Distributor",
	1: "LenderSupervisor",
	2: "Lender",
	3: "BorrowerSupervisor",
	4: "Borrower",
}
var NodeType_value = map[string]int32{
	"Distributor":        0,
	"LenderSupervisor":   1,
	"Lender":             2,
	"BorrowerSupervisor": 3,
	"Borrower":           4,
}

func (x NodeType) String() string {
	return proto.EnumName(NodeType_name, int32(x))
}
func (NodeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type NodeStatus int32

const (
	NodeStatus_ACTIVE           NodeStatus = 0
	NodeStatus_SHUTTINGDOWN     NodeStatus = 1
	NodeStatus_SHUTDOWNCOMPLETE NodeStatus = 2
)

var NodeStatus_name = map[int32]string{
	0: "ACTIVE",
	1: "SHUTTINGDOWN",
	2: "SHUTDOWNCOMPLETE",
}
var NodeStatus_value = map[string]int32{
	"ACTIVE":           0,
	"SHUTTINGDOWN":     1,
	"SHUTDOWNCOMPLETE": 2,
}

func (x NodeStatus) String() string {
	return proto.EnumName(NodeStatus_name, int32(x))
}
func (NodeStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Base struct {
	Sender      []byte      `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Timestamp   int64       `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	NodeType    NodeType    `protobuf:"varint,3,opt,name=node_type,json=nodeType,enum=cheshbown.proto.NodeType" json:"node_type,omitempty"`
	MessageType MessageType `protobuf:"varint,4,opt,name=message_type,json=messageType,enum=cheshbown.proto.MessageType" json:"message_type,omitempty"`
	Work        []*Work     `protobuf:"bytes,5,rep,name=work" json:"work,omitempty"`
	Workers     []*Worker   `protobuf:"bytes,6,rep,name=workers" json:"workers,omitempty"`
}

func (m *Base) Reset()                    { *m = Base{} }
func (m *Base) String() string            { return proto.CompactTextString(m) }
func (*Base) ProtoMessage()               {}
func (*Base) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Base) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Base) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Base) GetNodeType() NodeType {
	if m != nil {
		return m.NodeType
	}
	return NodeType_Distributor
}

func (m *Base) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_WORK
}

func (m *Base) GetWork() []*Work {
	if m != nil {
		return m.Work
	}
	return nil
}

func (m *Base) GetWorkers() []*Worker {
	if m != nil {
		return m.Workers
	}
	return nil
}

type Work struct {
	Id           []byte    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created      int64     `protobuf:"varint,2,opt,name=created" json:"created,omitempty"`
	Retries      int32     `protobuf:"varint,3,opt,name=retries" json:"retries,omitempty"`
	Result       Result    `protobuf:"varint,4,opt,name=result,enum=cheshbown.proto.Result" json:"result,omitempty"`
	Data         []byte    `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	WorkersTried []*Worker `protobuf:"bytes,6,rep,name=workers_tried,json=workersTried" json:"workers_tried,omitempty"`
}

func (m *Work) Reset()                    { *m = Work{} }
func (m *Work) String() string            { return proto.CompactTextString(m) }
func (*Work) ProtoMessage()               {}
func (*Work) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Work) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Work) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Work) GetRetries() int32 {
	if m != nil {
		return m.Retries
	}
	return 0
}

func (m *Work) GetResult() Result {
	if m != nil {
		return m.Result
	}
	return Result_ACK
}

func (m *Work) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Work) GetWorkersTried() []*Worker {
	if m != nil {
		return m.WorkersTried
	}
	return nil
}

type Worker struct {
	Id       []byte     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeType NodeType   `protobuf:"varint,2,opt,name=node_type,json=nodeType,enum=cheshbown.proto.NodeType" json:"node_type,omitempty"`
	LastSeen int64      `protobuf:"varint,3,opt,name=last_seen,json=lastSeen" json:"last_seen,omitempty"`
	Status   NodeStatus `protobuf:"varint,4,opt,name=status,enum=cheshbown.proto.NodeStatus" json:"status,omitempty"`
}

func (m *Worker) Reset()                    { *m = Worker{} }
func (m *Worker) String() string            { return proto.CompactTextString(m) }
func (*Worker) ProtoMessage()               {}
func (*Worker) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Worker) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Worker) GetNodeType() NodeType {
	if m != nil {
		return m.NodeType
	}
	return NodeType_Distributor
}

func (m *Worker) GetLastSeen() int64 {
	if m != nil {
		return m.LastSeen
	}
	return 0
}

func (m *Worker) GetStatus() NodeStatus {
	if m != nil {
		return m.Status
	}
	return NodeStatus_ACTIVE
}

func init() {
	proto.RegisterType((*Base)(nil), "cheshbown.proto.Base")
	proto.RegisterType((*Work)(nil), "cheshbown.proto.Work")
	proto.RegisterType((*Worker)(nil), "cheshbown.proto.Worker")
	proto.RegisterEnum("cheshbown.proto.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("cheshbown.proto.Result", Result_name, Result_value)
	proto.RegisterEnum("cheshbown.proto.NodeType", NodeType_name, NodeType_value)
	proto.RegisterEnum("cheshbown.proto.NodeStatus", NodeStatus_name, NodeStatus_value)
}

func init() { proto.RegisterFile("credit.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 526 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xdd, 0x6e, 0xda, 0x4c,
	0x10, 0xc5, 0x3f, 0x18, 0x33, 0xf8, 0x23, 0xab, 0xd1, 0xd7, 0xd4, 0x15, 0xb9, 0x40, 0x5c, 0x51,
	0x2e, 0xa8, 0x9a, 0x48, 0xbd, 0xaa, 0xd4, 0x26, 0x80, 0x52, 0x54, 0x30, 0xd1, 0xda, 0x29, 0x97,
	0xc8, 0xe0, 0x55, 0x63, 0x25, 0xd8, 0x68, 0x77, 0x29, 0xca, 0x73, 0xf4, 0x0d, 0xfa, 0x3e, 0x7d,
	0xa7, 0x6a, 0x17, 0x5b, 0x34, 0x25, 0x52, 0x7b, 0xe5, 0x99, 0x33, 0xe7, 0xcc, 0xec, 0x99, 0x31,
	0x78, 0x2b, 0xce, 0x92, 0x54, 0xf6, 0x37, 0x3c, 0x97, 0x39, 0x9e, 0xac, 0xee, 0x98, 0xb8, 0x5b,
	0xe6, 0xbb, 0x6c, 0x0f, 0x74, 0xbe, 0x9b, 0x60, 0x5f, 0xc5, 0x82, 0xe1, 0x29, 0x38, 0x82, 0x65,
	0x09, 0xe3, 0xbe, 0xd1, 0x36, 0xba, 0x1e, 0x2d, 0x32, 0x3c, 0x83, 0xba, 0x4c, 0xd7, 0x4c, 0xc8,
	0x78, 0xbd, 0xf1, 0xcd, 0xb6, 0xd1, 0xb5, 0xe8, 0x01, 0xc0, 0x77, 0x50, 0xcf, 0xf2, 0x84, 0x2d,
	0xe4, 0xe3, 0x86, 0xf9, 0x56, 0xdb, 0xe8, 0x36, 0xcf, 0x5f, 0xf5, 0xff, 0x98, 0xd1, 0x0f, 0xf2,
	0x84, 0x45, 0x8f, 0x1b, 0x46, 0xdd, 0xac, 0x88, 0xf0, 0x03, 0x78, 0x6b, 0x26, 0x44, 0xfc, 0xb5,
	0x90, 0xda, 0x5a, 0x7a, 0x76, 0x24, 0x9d, 0xee, 0x49, 0x5a, 0xdd, 0x58, 0x1f, 0x12, 0x7c, 0x0d,
	0xf6, 0x2e, 0xe7, 0xf7, 0x7e, 0xb5, 0x6d, 0x75, 0x1b, 0xe7, 0x2f, 0x8e, 0x84, 0xf3, 0x9c, 0xdf,
	0x53, 0x4d, 0xc1, 0xb7, 0x50, 0x53, 0x5f, 0xc6, 0x85, 0xef, 0x68, 0xf6, 0xcb, 0x67, 0xd9, 0x8c,
	0xd3, 0x92, 0xd7, 0xf9, 0x69, 0x80, 0xad, 0x30, 0x6c, 0x82, 0x99, 0x26, 0xc5, 0x46, 0xcc, 0x34,
	0x41, 0x1f, 0x6a, 0x2b, 0xce, 0x62, 0xc9, 0x92, 0x62, 0x17, 0x65, 0xaa, 0x2a, 0x9c, 0x49, 0x9e,
	0x32, 0xa1, 0xf7, 0x50, 0xa5, 0x65, 0x8a, 0x6f, 0xc0, 0xe1, 0x4c, 0x6c, 0x1f, 0x64, 0xe1, 0xf2,
	0x78, 0x3c, 0xd5, 0x65, 0x5a, 0xd0, 0x10, 0xc1, 0x4e, 0x62, 0x19, 0xfb, 0x55, 0x3d, 0x56, 0xc7,
	0xf8, 0x1e, 0xfe, 0x2b, 0x1e, 0xb7, 0x50, 0x5d, 0x93, 0xbf, 0x59, 0xf1, 0x0a, 0x76, 0xa4, 0xc8,
	0x9d, 0x1f, 0x06, 0x38, 0xfb, 0xc2, 0x91, 0xa3, 0x27, 0x17, 0x34, 0xff, 0xfd, 0x82, 0x2d, 0xa8,
	0x3f, 0xc4, 0x42, 0x2e, 0x04, 0x63, 0x99, 0x76, 0x6c, 0x51, 0x57, 0x01, 0x21, 0x63, 0x19, 0x5e,
	0x80, 0x23, 0x64, 0x2c, 0xb7, 0xa2, 0xb0, 0xdc, 0x7a, 0xb6, 0x63, 0xa8, 0x29, 0xb4, 0xa0, 0xf6,
	0xa6, 0xd0, 0xf8, 0xed, 0xdc, 0xe8, 0x82, 0x3d, 0x9f, 0xd1, 0xcf, 0xa4, 0x82, 0x4d, 0x80, 0xe1,
	0x38, 0x1c, 0xcc, 0x82, 0x60, 0x34, 0x88, 0x88, 0x81, 0x1e, 0xb8, 0xe1, 0xa7, 0xdb, 0x68, 0x38,
	0x9b, 0x07, 0xc4, 0x44, 0x00, 0x87, 0x8e, 0xc2, 0xdb, 0x49, 0x44, 0x2c, 0x15, 0x5f, 0xcf, 0xc2,
	0x70, 0x7c, 0x43, 0xec, 0x5e, 0x0b, 0x9c, 0xfd, 0x5e, 0xb1, 0x06, 0xd6, 0xe5, 0x40, 0x35, 0x72,
	0xc1, 0x0e, 0x54, 0x64, 0xf4, 0x56, 0xe0, 0x96, 0x9e, 0xf0, 0x04, 0x1a, 0xc3, 0x54, 0x48, 0x9e,
	0x2e, 0xb7, 0x32, 0xe7, 0xa4, 0x82, 0xff, 0x03, 0x99, 0xe8, 0x9f, 0x3f, 0xdc, 0x6e, 0x18, 0xff,
	0x96, 0x8a, 0x9c, 0x13, 0x43, 0xf5, 0xde, 0xa3, 0xc4, 0xc4, 0x53, 0xc0, 0xab, 0x9c, 0xf3, 0x7c,
	0xf7, 0x84, 0x63, 0xa9, 0x97, 0x95, 0x38, 0xb1, 0x7b, 0x1f, 0x01, 0x0e, 0x36, 0x95, 0xfe, 0x72,
	0x10, 0x8d, 0xbf, 0x8c, 0x48, 0x05, 0x09, 0x78, 0xca, 0x41, 0x34, 0x0e, 0xae, 0xb5, 0x0b, 0x43,
	0xcd, 0x2c, 0x3d, 0x0d, 0x66, 0xd3, 0x9b, 0xc9, 0x28, 0x1a, 0x11, 0x73, 0xe9, 0xe8, 0x65, 0x5d,
	0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x31, 0x3d, 0xbc, 0xb9, 0xc5, 0x03, 0x00, 0x00,
}
